### ISSUE TITLE
plot - change dependencies with python3.7

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#149]
- [x] multiqc problem
- [x] openpyxl problem (reactivate new environment for each server!)
- [x] TypeError: 'LineCollection' object is not iterable

old instructions - remove if tests ok!

(Wochenende_plot only). Install the python dependencies for visualization by pip. The works on Ubuntu 1604: 
`pip3 install --user numpy==1.12.1 numpy-base==1.15.0 pandas==0.23.4 matplotlib==2.2.2
`

New package versions in July 2021 `env.wochenende.minimal.yml`

```

grep numpy *
grep: dependencies: Is a directory
env.wochenende.minimal.yml:  - numpy=1.20.2=py37h2d18471_0
env.wochenende.minimal.yml:  - numpy-base=1.20.2=py37hfae3a4d_0
env.wochenende.yml:  - numpy=1.12.1
env.wochenende.yml:  - numpy-base=1.15.0

README.md:7. (Wochenende_plot only). Install the python dependencies for visualization by pip. The works on Ubuntu 1604: `pip3 install --user numpy==1.12.1 numpy-base==1.15.0 pandas==0.23.4 matplotlib==2.2.2`

 grep pand *
env.wochenende.minimal.yml:  - pandas=1.2.5=py37h295c915_0
env.wochenende.yml:  - pandas=0.23.4
README.md:7. (Wochenende_plot only). Install the python dependencies for visualization by pip. The works on Ubuntu 1604: `pip3 install --user numpy==1.12.1 numpy-base==1.15.0 pandas==0.23.4 matplotlib==2.2.2`
run_Wochenende.py:        type=lambda x: (os.path.abspath(os.path.expanduser(x))),

grep matplo *
env.wochenende.minimal.yml:  - matplotlib=3.3.4=py37h06a4308_0
env.wochenende.minimal.yml:  - matplotlib-base=3.3.4=py37h62a2d02_0

```

**Comment by colindaven** [comment]
Updating with `multiqc` causes problems.

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - python==3.7.10=h12debd9_4 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

```

Another omission from our env:

`ModuleNotFoundError: No module named 'openpyxl'
`

**Comment by colindaven** [comment]
Another omission from our env:

`ModuleNotFoundError: No module named 'openpyxl'
`

**Comment by colindaven** [comment]
After solving above problems now getting LineCollection object not iterable error

```
Traceback (most recent call last):
  File "wochenende_plot.py", line 824, in <module>
    main()
  File "wochenende_plot.py", line 812, in main
    sample_outpath
  File "wochenende_plot.py", line 779, in calculate_scores
    other
  File "wochenende_plot.py", line 515, in generate_output
    simplified_max_mean_coverage,
  File "wochenende_plot.py", line 287, in plot_figures
    for stem in stems:
TypeError: 'LineCollection' object is not iterable
```
