### ISSUE TITLE
visualize coverage profiles of bacteria

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#16]
- [x] python pandas script
- [x] simple bar / hist /line diags of each species
- [x] exclude ignore human/mouse chr reads
- [x] Terms for image subfolders: `probably_present, potentially_present`
- [x] Only produce pictures when 5+ windows are present (else >1000 pictures per BAM file)
- [x] Stats in additional stats file. Stats for all hits in BAM file, i.e. disregard 5+ rule above

**Comment by colindaven** [comment]
Install testing:
`pip3 install --user numpy==1.17.4 pandas==0.24.2 matplotlib==3.0.3`

Error on non-GUI server - qt from within a conda env.



Traceback (most recent call last):
  File "wochenende_plot.py", line 19, in <module>
    import matplotlib.pyplot as plt
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 140, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by colindaven** [comment]
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

**Comment by colindaven** [comment]
# We need to use agg before importing pyplot

import csv
import argparse
import pandas as pd
import matplotlib
# Use Agg to avoid requiring qt
matplotlib.use('agg')
import matplotlib.pyplot as plt
import numpy as np
import os
import math
import statistics

**Comment by colindaven** [comment]
Now completed, thanks to @konnosif
