### ISSUE TITLE
growth rate problems

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#167]
@poer-sophia 

Note to self: if problems occur calculation growth rates, delete and recreate the `growth_rate` folder using `get_wochenende.sh`

**Comment by colindaven** [comment]
string, float conversion, growth rates

I```
NFO: working on organism NC_015678.1_Streptococcus_parasanguinis_ATCC_15912__complete_sequence
INFO: working on organism NC_013715.1_Rothia_mucilaginosa_DY_18__complete_genome
INFO: working on organism NZ_LR134375.1_Veillonella_dispar_strain_NCTC11831_chromosome_1
INFO: working on organism NZ_LR134266.1_Streptococcus_viridans_strain_NCTC3166_chromosome_1
INFO: working on organism NC_015875.1_Streptococcus_pseudopneumoniae_IS7493__complete_sequence
INFO: working on organism NZ_LS483444.1_Streptococcus_australis_strain_NCTC13166_chromosome_1
INFO: Completed file 4_sm_R1.ndp.trm.s.mm.dup.mq30.calmd.bed
cleanup: unlink bam, bai and bam.txt files
^M  0%|          | 0/29 [00:00<?, ?it/s]^M  0%|          | 0/29 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    main()
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "main.py", line 74, in main
    save_plots=True)
  File "main.py", line 38, in evaluate_all_data
    high_res_plot=False)
  File "/ngsssd1/rcug/wochenende_test/CF_small/growth_rate/model.py", line 59, in compute_ptr
    csv_data = read_csv(csv_path)
  File "/ngsssd1/rcug/wochenende_test/CF_small/growth_rate/model.py", line 8, in read_csv
    return pd.read_csv(csv_path, header=None, float_precision='high').to_numpy(dtype='float64').flatten()
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/pandas/core/frame.py", line 1436, in to_numpy
    transpose=self._AXIS_REVERSED, dtype=dtype, copy=copy, na_value=na_value
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 870, in as_array
    arr = arr.astype(dtype, copy=False)
ValueError: could not convert string to float: 'NC_013715.1_Rothia_mucilaginosa_DY_18__complete_genome\t2264603\t35165\t0'
working on sample 5_sm_R1.ndp.trm.s.mm.dup.mq30.calmd_subsamples
```

**Comment by colindaven** [comment]
Solution: 

core dumps and strange behaviour may occur if the correct conda env, with pandas etc, is not activated when running the growth rate module.

```
  # following line causes core dumps if the correct conda environment with pandas etc is not activated
  python3 bed_to_pos_csv.py -i $filtBedFile -p .
```

**Comment by colindaven** [comment]
Removed & which was causing waits to fail in `runbatch_bed_to_csv.sh`
