### ISSUE TITLE
growth rate - exclude 1,2,3,4 etc

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#168]
Exclude single char chromosomes like 1 (eg from mouse chr).

Else get this problem:

@poer-sophia Am trying a workaround (to avoid this crash, not that I really want to calculate "growth_rates" for mouse chr 1...

`str(organism)
`
```
/site-packages/click/core.py:1404: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memor
y=False.
  return ctx.invoke(self.callback, **ctx.params)
INFO: working on organism 1
Traceback (most recent call last):
  File "bed_to_pos_csv.py", line 79, in <module>
    main()
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/ngsnfs/tools/miniconda3/envs/wochenende/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "bed_to_pos_csv.py", line 75, in main
    get_pos(df_input_file, input_file, input_path, plot_samples, min_read_count)
  File "bed_to_pos_csv.py", line 26, in get_pos
    save_as_csv(filename, path, normalised_position, organism)
  File "bed_to_pos_csv.py", line 63, in save_as_csv
    path + '/' + file.replace(".bed", "_" + organism + ".csv"),
TypeError: can only concatenate str (not "int") to str
INFO: working on organism 1

```

**Comment by colindaven** [comment]
I ended up reformatting the mouse GRCm39 input genome to include chr1, not just 1.
