### ISSUE TITLE
Aligner not chosen - leads to bug

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#8]
Example command, --aligner not defined
python3 run_Wochenende.py --metagenome 2016_06_1p_spec_corrected --threads 12 --no_abra --readType SE --debug $fastq

######  Alignment  ######
Traceback (most recent call last):
  File "run_Wochenende.py", line 623, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "run_Wochenende.py", line 531, in main
    args.threads, args.readType)
  File "run_Wochenende.py", line 135, in runFunc
    cF = func(cF, *extraArgs)
  File "run_Wochenende.py", line 381, in runAligner
    if "minimap2" in aligner:
TypeError: argument of type 'NoneType' is not iterable

Solution: default=bwamem

Is this ok @B1T0 ? Or should we make aligner choice a required non-positional argument?

**Comment by colindaven** [comment]
Solved
