### ISSUE TITLE
wochenende plot error b: exotic headers ?

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#84]
Project 2020_035351

```
Traceback (most recent call last):
  File "wochenende_plot.py", line 450, in <module>
    organism4=i.split("_")[6]
IndexError: list index out of range
Traceback (most recent call last):
  File "wochenende_plot.py", line 450, in <module>
    organism4=i.split("_")[6]
IndexError: list index out of range
```

**Comment by colindaven** [comment]
Also here:

/ngsssd1/rcug/wochenende_test/pilz/plots$ bash runbatch_wochenende_plot.sh
Traceback (most recent call last):
  File "wochenende_plot.py", line 450, in <module>
    organism4=i.split("_")[6]
IndexError: list index out of range

**Comment by colindaven** [comment]
@poer-sophia Can you please have a look to see if you can reproduce this error ? 
The plotting needs to be rewritten/ refactored into methods, but to start with can you please

a) clone the dev branch (or better download and make an internal git repo with the plotting code only)

b) Try to replicate the error

c) Add try/ catch statements to catch and output error lines and make parsing safer (this was a different reference to that which the program was originally written for).

Thanks,
Colin

**Comment by colindaven** [comment]
Being done in local repo
